FROM golang:1.18-alpine

LABEL maintainer="james.y.yang@newegg.com"

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

RUN apk add --no-cache --virtual .build-deps make clang llvm bash dumb-init tzdata

WORKDIR /dist

COPY ./assets /dist/assets

COPY ./config /dist/config

COPY ./ebpf /dist/ebpf

COPY ./modules /dist/modules

COPY ./k8s /dist/k8s

COPY ./go.mod /dist/

COPY ./go.sum /dist/

COPY ./mbpf.go /dist/

COPY ./Makefile /dist/

RUN go env -w GOPROXY=https://goproxy.cn,direct

RUN make

ENTRYPOINT ["dumb-init", "--"]

CMD ["./mbpf"]