WokerConfig:
  EBPFSysExecve: 
    Name: EBPFSysExecve
    Enable: true
  EBPFSysOpenat: 
    Name: EBPFSysOpenat
    Enable: false
  EBPFTCPConnectProbe: 
    Name: EBPFTCPConnectProbe
    Enable: false
  EBPFTCPRetransProbe: 
    Name: EBPFTCPRetransProbe
    Enable: false
  EBPFTCPRSTProbe: 
    Name: EBPFTCPRSTProbe
    Enable: false