apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: sdfsdfsdfsd
      server: https://172.20.171.110:443
    name: myk8s
contexts:
  - context:
      cluster: myk8s
      namespace: default
      user: nes-view
    name: myk8s
current-context: myk8s
kind: Config
preferences: {}
users:
  - name: nes-view
    user:
      token: sdfsdfsdf