EndpointList:
  - Host: nginx-test
    IP: 172.17.0.2
    Type: Pod
  - Host: nginx2
    IP: 172.17.0.3
    Type: Pod
  - Host: www.baidu.com
    IP: 10.16.75.24
    Type: Service
  - Host: local
    IP: 192.168.146.128
    Type: Service
  - Host: james-windows
    IP: 192.168.146.1
    Type: Service
    Svc: test-service
    NS: hello